source: "_source"
destination: "_site"

# Used for build/deploy to remove things (styleguide, documentation)
isProduction : true

permalink : /blerg/:categories/:title
timezone : Australia/Melbourne
markdown: kramdown
highlighter : null
paginate : 5
paginate_path: "/blerg/page:num/"

kramdown:
  use_coderay: true
  coderay_css: class
  coderay_line_numbers: nil
