source: "_source"
destination: "_site"

# Used for build/deploy to remove things (styleguide, documentation)
isProduction : true

permalink : /blerg/:categories/:title
timezone : Australia/Melbourne
markdown: kramdown
highlighter : rouge
paginate_path: "/blerg/page:num/"
exclude: ["documentation", "*.scss", "theme/mohawk/scripts/"]


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "mohawk/blog-detail"
      body__class: "standard"
